### ISSUE TITLE
Undefined command raises error and kills the shell

### ISSUE THREAD

**Issue by Vafa-Andalibi** [cloudmesh/cloudmesh-cmd5#4]
Example: 

```
cms> whatever
Traceback (most recent call last):
  File "/home/corriel/gitrepos/courses/cloudmesh/cloudmesh.cmd5/cloudmesh/shell/shell.py", line 288, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'CMShell' object has no attribute 'do_whatever'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/corriel/.local/share/virtualenvs/cloudmesh-fFt_DZFB/bin/cms", line 11, in <module>
    load_entry_point('cloudmesh.cmd5', 'console_scripts', 'cms')()
  File "/home/corriel/gitrepos/courses/cloudmesh/cloudmesh.cmd5/cloudmesh/shell/shell.py", line 846, in main
    cmd.cmdloop()
  File "/usr/local/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/corriel/gitrepos/courses/cloudmesh/cloudmesh.cmd5/cloudmesh/shell/shell.py", line 293, in onecmd
    trace = "T" in vars['trace']
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by laszewsk** [comment]
uninstall cmd5, common, sys 

and reinstall

see what happens

**Comment by laszewsk** [comment]
also 

cms set trace=True
cms set trace=False

**Comment by Vafa-Andalibi** [comment]
I just re-cloned and reinstalled all in a new folder and environment (Ubuntu 18.04, Pipenv) but still the same. The `cms set trace` applied successfully but didn't affect the error (still the error). I was just checking this part:

```
        if cmd != '':
            try:
                func = getattr(self, 'do_' + cmd)
                return func(arg)
            except AttributeError as e:

                vars = Variables()
                trace = "T" in vars['trace']
                debug = "T" in vars['debug']

                Console.error("command error while executing '{cmd}'".format(cmd=cmd),
                              traceflag=trace)
                cmd = None
                line = oldline




                Error.traceback(error=e, debug=debug, trace=trace)
        return ""
``` 
There is an instance of `Variables()` and that instance is reading from `~/.cloudmesh/var-data` which expect it to have `trace` and `debug` set in it. The content of `var-data` in my machine is this only: 

```$ cat ~/.cloudmesh/var-data 
timer: 'off'
trace: 'True'
``` 
where are the `trace` and `debug` initiated?

**Comment by laszewsk** [comment]
You not only need to clone but best is to do it in a new pyenv

**Comment by Vafa-Andalibi** [comment]
I'll try a clean installation with pyenv and post updates here.

**Comment by laszewsk** [comment]
if the command is not defined an error is caught and a warning msg is thrown
